"""content and bookmarks

Revision ID: 4896c58355f9
Revises: 0001
Create Date: 2026-09-29 05:41:05.851614+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4896c58355f9"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("key", name=op.f("uq_tags_key")),
    )
    op.create_table(
        "articles",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column(
            "article_type",
            sa.Enum("news", "opinion", "analysis", "feature", "interview", name="article_type"),
            nullable=False,
        ),
        sa.Column("lead_media_id", sa.Uuid(), nullable=True),
        sa.Column("is_breaking", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_articles_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_articles_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
    )
    op.create_index(op.f("ix_articles_section_id"), "articles", ["section_id"], unique=False)
    op.create_table(
        "authors",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind", sa.Enum("staff", "contributor", "agency", name="author_kind"), nullable=False
        ),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_authors_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("key", name=op.f("uq_authors_key")),
        sa.UniqueConstraint("user_id", name=op.f("uq_authors_user_id")),
    )
    op.create_table(
        "tag_translations",
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_tag_translations_locale_locales")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_tag_translations_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag_translations")),
        sa.UniqueConstraint("locale", "slug", name=op.f("uq_tag_translations_locale_slug")),
        sa.UniqueConstraint("tag_id", "locale", name=op.f("uq_tag_translations_tag_id_locale")),
    )
    op.create_table(
        "article_authors",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_authors_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("fk_article_authors_author_id_authors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("article_id", "author_id", name=op.f("pk_article_authors")),
    )
    op.create_table(
        "article_localizations",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_review",
                "copy_editing",
                "changes_requested",
                "approved",
                "scheduled",
                "published",
                "unpublished",
                "killed",
                "archived",
                name="article_status",
            ),
            nullable=False,
        ),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("published_revision_id", sa.Uuid(), nullable=True),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unpublish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("update_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("legal_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "deleted_at IS NULL OR first_published_at IS NULL",
            name=op.f("ck_article_localizations_deleted_never_published"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_localizations_article_id_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_article_localizations_locale_locales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_localizations")),
        sa.UniqueConstraint(
            "article_id", "locale", name=op.f("uq_article_localizations_article_id_locale")
        ),
        sa.UniqueConstraint("locale", "slug", name=op.f("uq_article_localizations_locale_slug")),
    )
    op.create_index(
        op.f("ix_article_localizations_article_id"),
        "article_localizations",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        "ix_article_localizations_public",
        "article_localizations",
        ["locale", "published_at"],
        unique=False,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_index(
        "ix_article_localizations_scheduled",
        "article_localizations",
        ["publish_at"],
        unique=False,
        postgresql_where=sa.text("status = 'scheduled'"),
    )
    op.create_table(
        "article_tags",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_tags_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_article_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("article_id", "tag_id", name=op.f("pk_article_tags")),
    )
    op.create_table(
        "author_translations",
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("fk_author_translations_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_author_translations_locale_locales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author_translations")),
        sa.UniqueConstraint(
            "author_id", "locale", name=op.f("uq_author_translations_author_id_locale")
        ),
        sa.UniqueConstraint("locale", "slug", name=op.f("uq_author_translations_locale_slug")),
    )
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_bookmarks_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bookmarks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "article_id", name=op.f("pk_bookmarks")),
    )
    op.create_table(
        "article_revisions",
        sa.Column("localization_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.Uuid(), nullable=True),
        sa.Column("restored_from_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("manual", "autosave", "restore", "system", name="revision_kind"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("excerpt", sa.String(length=1000), nullable=True),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("seo_title", sa.String(length=300), nullable=True),
        sa.Column("seo_description", sa.String(length=500), nullable=True),
        sa.Column("change_note", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_article_revisions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["article_localizations.id"],
            name=op.f("fk_article_revisions_localization_id_article_localizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_revisions")),
        sa.UniqueConstraint(
            "localization_id",
            "revision_no",
            name=op.f("uq_article_revisions_localization_id_revision_no"),
        ),
    )
    op.create_index(
        op.f("ix_article_revisions_localization_id"),
        "article_revisions",
        ["localization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_localizations_current_revision",
        "article_localizations",
        "article_revisions",
        ["current_revision_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_localizations_published_revision",
        "article_localizations",
        "article_revisions",
        ["published_revision_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_revisions_parent",
        "article_revisions",
        "article_revisions",
        ["parent_revision_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_revisions_restored_from",
        "article_revisions",
        "article_revisions",
        ["restored_from_id"],
        ["id"],
    )
    op.create_table(
        "corrections",
        sa.Column("localization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("correction", "clarification", "update", name="correction_kind"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_corrections_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["article_localizations.id"],
            name=op.f("fk_corrections_localization_id_article_localizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrections")),
    )
    op.create_index(
        op.f("ix_corrections_localization_id"), "corrections", ["localization_id"], unique=False
    )
    op.create_table(
        "slug_redirects",
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("old_slug", sa.String(length=200), nullable=False),
        sa.Column("localization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_slug_redirects_locale_locales")
        ),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["article_localizations.id"],
            name=op.f("fk_slug_redirects_localization_id_article_localizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("locale", "old_slug", name=op.f("pk_slug_redirects")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_localizations_current_revision", "article_localizations", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_localizations_published_revision", "article_localizations", type_="foreignkey"
    )
    op.drop_constraint("fk_revisions_parent", "article_revisions", type_="foreignkey")
    op.drop_constraint("fk_revisions_restored_from", "article_revisions", type_="foreignkey")
    op.drop_table("slug_redirects")
    op.drop_index(op.f("ix_corrections_localization_id"), table_name="corrections")
    op.drop_table("corrections")
    op.drop_index(op.f("ix_article_revisions_localization_id"), table_name="article_revisions")
    op.drop_table("article_revisions")
    op.drop_table("bookmarks")
    op.drop_table("author_translations")
    op.drop_table("article_tags")
    op.drop_index(
        "ix_article_localizations_scheduled",
        table_name="article_localizations",
        postgresql_where=sa.text("status = 'scheduled'"),
    )
    op.drop_index(
        "ix_article_localizations_public",
        table_name="article_localizations",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_index(op.f("ix_article_localizations_article_id"), table_name="article_localizations")
    op.drop_table("article_localizations")
    op.drop_table("article_authors")
    op.drop_table("tag_translations")
    op.drop_table("authors")
    op.drop_index(op.f("ix_articles_section_id"), table_name="articles")
    op.drop_table("articles")
    op.drop_table("tags")
    for enum_name in (
        "correction_kind",
        "revision_kind",
        "article_status",
        "author_kind",
        "article_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
