"""media homepage newsletters comments

Revision ID: 6252d3aa14cf
Revises: b7e2c1a94f08
Create Date: 2026-09-29 08:38:21.107316+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6252d3aa14cf"
down_revision: str | Sequence[str] | None = "b7e2c1a94f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _search_functions() -> None:
    # Diacritics, tatweel, and Quranic marks. Folded so موازنة and موازنه share a lexeme.
    strip = (
        "\u0640"
        + "".join(chr(code) for code in range(0x0610, 0x061B))
        + "".join(chr(code) for code in range(0x064B, 0x0660))
        + "\u0670"
        + "".join(chr(code) for code in range(0x06D6, 0x06EE))
    )
    op.execute(
        f"""
        CREATE FUNCTION search_normalize(input text)
        RETURNS text
        LANGUAGE sql
        STABLE
        PARALLEL SAFE
        AS $$
          SELECT translate(
            regexp_replace(coalesce(input, ''), '[{strip}]', '', 'g'),
            'أإآٱىة',
            'اااايه'
          );
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION search_prefix_tsquery(config regconfig, term text)
        RETURNS tsquery
        LANGUAGE sql
        STABLE
        PARALLEL SAFE
        AS $$
          SELECT CASE
            WHEN compiled IS NULL OR compiled = '' THEN NULL
            ELSE to_tsquery(config, compiled)
          END
          FROM (
            SELECT string_agg(quote_literal(lexeme) || ':*', ' | ') AS compiled
            FROM unnest(to_tsvector(config, search_normalize(term))) AS t(lexeme, positions)
          ) AS parts;
        $$
        """
    )


def upgrade() -> None:
    _search_functions()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("mime_type", sa.String(length=80), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("credit", sa.String(length=200), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_media_assets_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    op.create_table(
        "newsletter_issues",
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("edition_date", sa.Date(), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("story_slugs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_newsletter_issues_locale_locales")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletter_issues")),
        sa.UniqueConstraint(
            "locale", "edition_date", name=op.f("uq_newsletter_issues_locale_edition_date")
        ),
    )
    op.create_table(
        "media_translations",
        sa.Column("media_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_media_translations_locale_locales")
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_assets.id"],
            name=op.f("fk_media_translations_media_id_media_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("media_id", "locale", name=op.f("pk_media_translations")),
    )
    op.create_table(
        "newsletter_deliveries",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["newsletter_issues.id"],
            name=op.f("fk_newsletter_deliveries_issue_id_newsletter_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_newsletter_deliveries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", "user_id", name=op.f("pk_newsletter_deliveries")),
    )
    op.create_table(
        "comments",
        sa.Column("localization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["article_localizations.id"],
            name=op.f("fk_comments_localization_id_article_localizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_comments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(
        "ix_comments_localization_created",
        "comments",
        ["localization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "homepage_slots",
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("localization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locale"], ["locales.code"], name=op.f("fk_homepage_slots_locale_locales")
        ),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["article_localizations.id"],
            name=op.f("fk_homepage_slots_localization_id_article_localizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("locale", "position", name=op.f("pk_homepage_slots")),
        sa.UniqueConstraint(
            "locale", "localization_id", name=op.f("uq_homepage_slots_locale_localization_id")
        ),
    )
    op.create_foreign_key(
        op.f("fk_articles_lead_media_id_media_assets"),
        "articles",
        "media_assets",
        ["lead_media_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_articles_lead_media_id_media_assets"), "articles", type_="foreignkey"
    )
    op.drop_table("homepage_slots")
    op.drop_index("ix_comments_localization_created", table_name="comments")
    op.drop_table("comments")
    op.drop_table("newsletter_deliveries")
    op.drop_table("media_translations")
    op.drop_table("newsletter_issues")
    op.drop_table("media_assets")
    op.execute("DROP FUNCTION IF EXISTS search_prefix_tsquery(regconfig, text)")
    op.execute("DROP FUNCTION IF EXISTS search_normalize(text)")
    # ### end Alembic commands ###
